import Head from 'next/head';
import Avatar from '@/components/Avatar';
import { TbGridDots } from 'react-icons/tb';
import { IoMdSearch } from 'react-icons/io';
import { HiMicrophone } from 'react-icons/hi';
import Image from 'next/image';
import Footer from '@/components/Footer';
import { useRef } from 'react';
import { useRouter } from 'next/router';
import { useSession } from 'next-auth/react';


export default function Home() {

  const searchInputRef = useRef(null);
  const router = useRouter();
  const { data: session } = useSession();

  const search = (e) => {
    e.preventDefault();
    const term = searchInputRef.current.value;

    if (!term) return;

    router.push(`/search?term=${term}`);

  }


  return (
    <>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex items-center justify-center w-full flex-col h-screen'>
        <header className='flex items-center w-full px-5 md:px-10 py-5 justify-between text-sm text-gray-600'>

          <div className='flex space-x-4 items-center'>
            <p className='hidden md:inline-flex hover:text-gray-900 cursor-pointer'>About</p>
            <p className='hidden md:inline-flex hover:text-gray-900 cursor-pointer'>Store</p>
            <p className='block md:hidden hover:text-gray-900 cursor-pointer'>All</p>
          </div>

          <div className='flex space-x-4 items-center'>
            <p className='hidden md:inline-flex hover:text-gray-900 cursor-pointer'>Gmail</p>
            <p className='hidden md:inline-flex hover:text-gray-900 cursor-pointer'>Images</p>
            <TbGridDots className='text-gray-600 hover:bg-gray-100 p-2 w-9 h-9 rounded-full cursor-pointer' />
            <Avatar url={'https://webtech-blog.vercel.app/_next/image?url=%2Favatar.jpg&w=3840&q=75' || session?.user?.image} />
          </div>

        </header>

        <form className='flex flex-col items-center space-y-6 my-auto container flex-grow py-4 mt-10'>
          <Image src={'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'} unoptimized alt='Google' width={1000} className='w-64 h-auto' height={1000} draggable='false' />

          <div className='flex sm:w-full my-5 hover:shadow-md focus-within:shadow-md max-w-md  rounded-full border px-5 py-2 items-center sm:max-w-xl lg:max-w-2xl'>
            <IoMdSearch className='w-5 h-5 text-gray-500' />
            <input ref={searchInputRef} type="search" placeholder='' className='flex-grow focus:outline-none rounded-full bg-white px-2' />
            <HiMicrophone className='w-5 h-5 text-gray-500 cursor-pointer' />
          </div>

          <div className='flex items-center justify-center gap-4 flex-row md:flex-row mt-8'>
            <button onClick={search} type='submit' className='text-gray-700 bg-gray-50 hover:bg-gray-200 transition ease-out px-4 py-2 rounded-md hover:shadow-sm text-sm'>Google Search</button>
            <button type='button' className='text-gray-700 bg-gray-50 hover:bg-gray-200 transition ease-out px-4 py-2 rounded-md hover:shadow-sm text-sm'>I'm Felling Lucky</button>
          </div>

          <div className='flex flex-col items-center mt-4 justify-center text-center'>
            <p className='text-gray-700 text-xs'>It’s Safer Internet Day! Learn how Google Password Manager secures every sign in</p>
          </div>

        </form>

        <Footer />

      </main>

    </>
  )
}
